import type { Work } from "./foundation/contracts";
import { coreWorks } from "./foundation/fixtures";

const additionalPublicWorks = [
  { id: "braises", authorId: "author-aminata-leroux", editionId: "edition-braises-fr-2022", title: "L’Inventaire des braises", author: "Aminata Leroux", meta: "Roman · 2022", year: "2022", genre: "Roman contemporain", language: "Français", rating: "4,2", ratingCount: "612 évaluations", cover: false, coverTone: "brick", lede: "Une archiviste rassemble les objets rescapés d’un incendie et découvre les récits que leurs propriétaires avaient choisi de taire.", synopsis: ["Dans un atelier municipal provisoire, Salomé photographie, décrit et classe ce que le feu a laissé derrière lui. Les objets les plus modestes deviennent peu à peu les fragments d’une histoire commune que personne ne savait encore raconter."] },
  { id: "neige", authorId: "author-ezra-vidal", editionId: "edition-neige-fr-2017", title: "Ce que sait la neige", author: "Ezra Vidal", meta: "Roman · 2017", year: "2017", genre: "Fiction littéraire", language: "Français", rating: "4,0", ratingCount: "428 évaluations", cover: false, coverTone: "slate", lede: "Dans un hôtel fermé pour l’hiver, un frère et une sœur relisent le carnet météorologique de leur grand-père.", synopsis: ["Chaque relevé de température semble correspondre à un événement que la famille a oublié. Tandis que la neige isole le bâtiment, les deux enfants devenus adultes tentent de distinguer les faits des légendes transmises avec eux."] },
  { id: "vergers", authorId: "author-lila-berthier", editionId: "edition-vergers-fr-2025", title: "Les Vergers de l’aube", author: "Lila Berthier", meta: "Roman · 2025", year: "2025", genre: "Roman choral", language: "Français", rating: "4,4", ratingCount: "296 évaluations", cover: false, coverTone: "sage", lede: "Avant la vente d’un verger familial, cinq voix racontent une même dernière récolte sans jamais décrire le même lieu.", synopsis: ["Du premier panier au repas de clôture, chaque membre de la famille traverse le domaine selon ses propres souvenirs. Le roman fait de cette récolte un passage entre ce qui s’hérite, ce qui se refuse et ce qui peut encore être transmis autrement."] },
  { id: "orbites", authorId: "author-sohan-belaid", editionId: "edition-orbites-fr-2023", title: "Nos Orbites minuscules", author: "Sohan Belaïd", meta: "Récit · 2023", year: "2023", genre: "Récit contemporain", language: "Français", rating: "4,1", ratingCount: "507 évaluations", cover: false, coverTone: "petrol", lede: "Un conducteur de tramway observe les habitudes de ses passagers jusqu’au jour où la ligne change définitivement de tracé.", synopsis: ["À chaque terminus, Malik consigne un détail aperçu pendant le trajet. Ces notes dessinent des vies qui se croisent à heure fixe, puis révèlent ce qu’une ville déplace lorsqu’elle modifie un parcours familier."] },
  { id: "porcelaine", authorId: "author-iris-valmont", editionId: "edition-porcelaine-fr-2016", title: "La Chambre de porcelaine", author: "Iris Valmont", meta: "Roman · 2016", year: "2016", genre: "Roman historique", language: "Français", rating: "3,9", ratingCount: "733 évaluations", cover: false, coverTone: "plum", lede: "Une apprentie peintre sur porcelaine glisse des paysages interdits dans les services commandés par une famille industrielle.", synopsis: ["Dans la manufacture, Héloïse apprend à répéter des motifs sans laisser paraître sa main. Elle transforme pourtant chaque assiette en message discret, jusqu’à composer un territoire que seuls les ouvriers savent reconnaître."] },
  { id: "pluie", authorId: "author-milo-castel", editionId: "edition-pluie-fr-2020", title: "Après la pluie verticale", author: "Milo Castel", meta: "Nouvelles · 2020", year: "2020", genre: "Recueil de nouvelles", language: "Français", rating: "4,3", ratingCount: "344 évaluations", cover: false, coverTone: "ochre", lede: "Douze histoires suivent l’eau d’un même orage à travers les étages, les rues et les sous-sols d’une ville.", synopsis: ["Chaque nouvelle reprend un détail abandonné par la précédente : une chaussure, un ticket, une phrase entendue dans une cage d’escalier. Le recueil fait circuler ses personnages sans leur imposer de rencontre."] },
  { id: "silences", authorId: "author-maya-khellaf", editionId: "edition-silences-fr-2024", title: "Une Géographie des silences", author: "Maya Khellaf", meta: "Essai · 2024", year: "2024", genre: "Essai littéraire", language: "Français", rating: "4,5", ratingCount: "219 évaluations", cover: false, coverTone: "slate", lede: "Une enquête sensible sur les lieux où l’on se tait ensemble, de la bibliothèque à la salle d’attente.", synopsis: ["Maya Khellaf observe le silence comme une forme de relation plutôt que comme une absence. Ses déplacements relient architecture, mémoire collective et gestes ordinaires dans une langue volontairement accessible."] },
  { id: "latitude", authorId: "author-tomas-reeves", editionId: "edition-latitude-fr-2021", title: "Latitude des absents", author: "Tomas Reeves", meta: "Roman · 2021", year: "2021", genre: "Roman d’aventure", language: "Français", rating: "4,0", ratingCount: "891 évaluations", cover: false, coverTone: "petrol", lede: "Un opérateur radio reçoit les messages d’une expédition disparue trente ans plus tôt sur une fréquence inutilisée.", synopsis: ["Les transmissions arrivent dans le désordre et contredisent les archives officielles. Pour les comprendre, Elias doit reconstituer moins un itinéraire qu’une décision collective longtemps effacée."] },
  { id: "argile", authorId: "author-june-marais", editionId: "edition-argile-fr-2019", title: "Les Mains d’argile", author: "June Marais", meta: "Roman · 2019", year: "2019", genre: "Roman familial", language: "Français", rating: "4,2", ratingCount: "655 évaluations", cover: false, coverTone: "ochre", lede: "Trois générations de céramistes se retrouvent autour d’un four que personne ne sait plus allumer.", synopsis: ["La remise en état du four oblige chacune à reprendre les gestes de l’autre. Dans la chaleur de l’atelier, les désaccords familiaux apparaissent comme autant de façons de façonner, réparer ou laisser une forme inachevée."] },
  { id: "courants", authorId: "author-nils-oberlin", editionId: "edition-courants-fr-2018", title: "La Carte des courants faibles", author: "Nils Oberlin", meta: "Récit · 2018", year: "2018", genre: "Récit de voyage", language: "Français", rating: "3,8", ratingCount: "268 évaluations", cover: false, coverTone: "sage", lede: "Un voyageur remonte un fleuve en ne s’arrêtant que dans les lieux absents de son guide.", synopsis: ["De halte en halte, le narrateur délaisse les monuments pour les embarcadères secondaires, les cafés sans enseigne et les histoires que personne ne pense à transmettre. Le trajet devient une méthode d’attention."] },
  { id: "constellations", authorId: "author-leonie-sato", editionId: "edition-constellations-fr-2025", title: "Constellations domestiques", author: "Léonie Sato", meta: "Nouvelles · 2025", year: "2025", genre: "Recueil de nouvelles", language: "Français", rating: "4,4", ratingCount: "183 évaluations", cover: false, coverTone: "plum", lede: "Dans chaque appartement d’un même immeuble, un objet ordinaire devient le centre d’un monde privé.", synopsis: ["Une lampe laissée allumée, un bol fêlé et une plante déplacée relient des habitants qui s’ignorent. Sans événement spectaculaire, le recueil montre comment les intimités dessinent une constellation commune."] },
  { id: "marees", authorId: "author-omar-faye", editionId: "edition-marees-fr-2022", title: "Les Marées intérieures", author: "Omar Faye", meta: "Poésie · 2022", year: "2022", genre: "Poésie", language: "Français", rating: "4,6", ratingCount: "147 évaluations", cover: false, coverTone: "brick", lede: "Un cycle de poèmes suit les mouvements de la mer jusque dans les chambres, les corps et les souvenirs.", synopsis: ["Les textes brefs d’Omar Faye déplacent le vocabulaire marin vers les gestes quotidiens. Chaque page fonctionne comme une laisse de mer : peu d’éléments, mais une histoire possible entre eux."] },
  { id: "atelier", authorId: "author-clemence-dorsay", editionId: "edition-atelier-fr-2015", title: "L’Atelier des heures creuses", author: "Clémence Dorsay", meta: "Roman · 2015", year: "2015", genre: "Fiction littéraire", language: "Français", rating: "4,1", ratingCount: "976 évaluations", cover: false, coverTone: "slate", lede: "Une relieuse ouvre son atelier la nuit à celles et ceux qui veulent réparer un livre sans en effacer les marques.", synopsis: ["Chaque volume confié à Alma porte une annotation, une tache ou une page manquante que son propriétaire refuse de perdre. Les réparations racontent lentement une autre histoire du quartier."] },
  { id: "oiseaux", authorId: "author-chiara-novak", editionId: "edition-oiseaux-fr-2020", title: "Là où dorment les oiseaux", author: "Chiara Novak", meta: "Roman · 2020", year: "2020", genre: "Roman initiatique", language: "Français", rating: "4,3", ratingCount: "588 évaluations", cover: false, coverTone: "sage", lede: "Une adolescente cartographie les refuges nocturnes des oiseaux pendant que sa famille prépare un départ qu’elle refuse.", synopsis: ["Ses observations commencent comme un moyen de rester dehors plus longtemps. Elles deviennent un langage pour comprendre les migrations, choisies ou subies, qui traversent sa propre maison."] },
  { id: "cuivre", authorId: "author-adam-senecal", editionId: "edition-cuivre-fr-2023", title: "Le Goût du cuivre", author: "Adam Sénécal", meta: "Roman · 2023", year: "2023", genre: "Roman social", language: "Français", rating: "3,9", ratingCount: "402 évaluations", cover: false, coverTone: "brick", lede: "Après la fermeture d’une fonderie, un ancien contremaître enregistre les sons du site avant sa démolition.", synopsis: ["Ce qui devait être un inventaire technique recueille aussi les voix, les rythmes et les colères d’un travail disparu. En réécoutant les bandes, Lucien découvre ce que sa position l’avait empêché d’entendre."] },
  { id: "papier", authorId: "author-selma-voisin", editionId: "edition-papier-fr-2024", title: "Le Pays sous le papier", author: "Selma Voisin", meta: "Roman · 2024", year: "2024", genre: "Fable contemporaine", language: "Français", rating: "4,2", ratingCount: "315 évaluations", cover: false, coverTone: "ochre", lede: "Une restauratrice découvre une ville dessinée sous les couches d’une affiche ancienne.", synopsis: ["À mesure qu’elle décolle le papier, de nouvelles rues apparaissent et certaines adresses de sa propre ville disparaissent. Son travail devient une enquête sur ce que les images recouvrent autant que sur ce qu’elles révèlent."] },
  { id: "distance", authorId: "author-helene-okafor", editionId: "edition-distance-fr-2018", title: "À Distance de voix", author: "Hélène Okafor", meta: "Récit · 2018", year: "2018", genre: "Récit épistolaire", language: "Français", rating: "4,0", ratingCount: "521 évaluations", cover: false, coverTone: "plum", lede: "Deux inconnues enregistrent des messages vocaux destinés à la même personne, sans savoir qu’elle ne les écoute plus.", synopsis: ["Les messages alternent, se répondent parfois par hasard et construisent une présence absente. Le récit explore ce que la voix conserve lorsque la conversation n’a plus lieu."] },
  { id: "semaphore", authorId: "author-basile-kern", editionId: "edition-semaphore-fr-2021", title: "Le Dernier sémaphore", author: "Basile Kern", meta: "Roman · 2021", year: "2021", genre: "Roman maritime", language: "Français", rating: "4,1", ratingCount: "674 évaluations", cover: false, coverTone: "petrol", lede: "Le gardien d’un poste côtier désaffecté continue de transmettre chaque soir un bulletin à des navires qui ne répondent plus.", synopsis: ["Quand une lumière lui répond au large, Joachim hésite entre reprendre le protocole et quitter enfin le poste. La côte devient le théâtre discret d’un dialogue dont aucun des participants ne connaît la langue."] },
] as const satisfies readonly Work[];

export const publicWorks: readonly Work[] = [...coreWorks, ...additionalPublicWorks];
